# Generated by Django 2.0.6 on 2021-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=128)),
                ('birth', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
